[package]
name = "generate-captcha"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
captcha = "*"
clap = "*"
rand = "*"
indicatif = "0.16.2"
rayon = "*"
